
services:
  app:
    image: raychat-todo:0.0.1
    ports:
      - 3000:3000
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_USER: 
      MONGO_PASS: 
      MONGO_DB: raychat-todo
    networks:
      - raychat-todo-network
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./temp/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - raychat-todo-network

networks:
  raychat-todo-network:
    driver: bridge